name: Auto-merge PRs from trusted bots
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' || github.actor == 'github-actions' }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit
      - name: Dependabot metadata
        id: metadata
        if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
        uses: dependabot/fetch-metadata@v2.5.0
        with:
          github-token: "${{ github.token }}"
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          GH_TOKEN: "${{ github.token }}"
          PR_URL: ${{github.event.pull_request.html_url}}
