name: Auto-merge PRs from trusted bots
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'github-actions' }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: 2754721
          private-key: ${{ secrets.ACTIONS_RECURSIVE_PRIVATE_KEY }}
      - name: Dependabot metadata
        id: metadata
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: step-security/dependabot-fetch-metadata@38d404f7e1742ae1cfa9b25ade9afa0c7a288e77 # v2.5.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{github.event.pull_request.html_url}}
