name: Auto-merge PRs from trusted bots
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'github-actions' }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Dependabot metadata
        id: metadata
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a # v2.5.0
        with:
          github-token: "${{ github.token }}"
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          GH_TOKEN: "${{ github.token }}"
          PR_URL: ${{github.event.pull_request.html_url}}
